### ISSUE TITLE
smbserver.js error

### ISSUE THREAD

**Issue by duanshuaimin** [adobe/node-smb-server#1]
Error: Cannot find module './defaultauthenticator'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/node-smb-server/lib/smbserver.js:25:28)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

**Comment by duanshuaimin** [comment]
./defaultauthenticator maybe ./defaultAuthenticator

**Comment by stefan-guggisberg** [comment]
thanks for reporting this issue! and sorry for the late reply...

fixed in commit e12aeb9
