### ISSUE TITLE
Issues running server on Windows & Kali

### ISSUE THREAD

**Issue by ash47** [adobe/node-smb-server#38]
I have run the server on both Windows and Kali, the server starts fine, however, when I attempt to connect to it via smbclient or by mounting a cifs share on Kali, it has errors.

`C:\Users\tester\Desktop\smb_test\test\node_modules\node-smb-server>node index.js
info: [SRV] logging initialized.
info: [SRV] configuration successfully read: C:\Users\tester\Desktop\smb_test\test\node_modules\node-smb-server\config.json
info: [SRV] [13220] SMB server started listening on port 8445
info: [SRV] established client connection #1 from [10.3.1.246:54703] -> [10.3.1.246:8445]
error: [SRV] uncaught exception: Cannot read property 'negotiateMsg' of undefined
TypeError: Cannot read property 'negotiateMsg' of undefined
    at handle (C:\Users\tester\Desktop\smb_test\test\node_modules\node-smb-server\lib\smb\cmd\session_setup_andx.js:142:15)
    at C:\Users\tester\Desktop\smb_test\test\node_modules\node-smb-server\lib\smb\handler.js:76:9
    at C:\Users\tester\Desktop\smb_test\test\node_modules\async\lib\async.js:181:20
    at iterate (C:\Users\tester\Desktop\smb_test\test\node_modules\async\lib\async.js:262:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (C:\Users\tester\Desktop\smb_test\test\node_modules\async\lib\async.js:281:9)
    at Object.async.forEachSeries.async.eachSeries (C:\Users\tester\Desktop\smb_test\test\node_modules\async\lib\async.js:214:22)
    at Object.handleRequest (C:\Users\tester\Desktop\smb_test\test\node_modules\node-smb-server\lib\smb\handler.js:63:9)
    at C:\Users\tester\Desktop\smb_test\test\node_modules\node-smb-server\lib\smbconnection.js:96:13
    at C:\Users\tester\Desktop\smb_test\test\node_modules\async\lib\async.js:181:20
    at Object.async.forEachOf.async.eachOf (C:\Users\tester\Desktop\smb_test\test\node_modules\async\lib\async.js:233:13)`

I've tried the NPM version and cloning the repo, I get the same error with both versions, same error if I host it on Windows 10 or Kali.

Happy to provide any further information that is needed.

**Comment by stefan-guggisberg** [comment]
thanks for reporting this issue. it seems like there's a problem with the initial handshake (sessionKey 
 passed in SMB_COM_SESSION_SETUP_ANDX msg seems to be invalid). this is most likely a client issue. have you tried to access the same server using Finder on a mac?

Finder is currently the only tested client. support for other clients and platforms is on the TODO list but, due to limited time, frankly not a very high priority.

**Comment by ash47** [comment]
I don't own a Mac lol, ggwp

**Comment by bchr02** [comment]
PC support would be awesome!

**Comment by stefan-guggisberg** [comment]
duplicated by https://github.com/adobe/node-smb-server/issues/43
